src/AdminBundle/Form/Type/CaptchaType.php
<?php
/**
 * Created by PhpStorm.
 * User: VanIllaSkyPE
 * Date: 25/03/2018
 * Time: 23:38.
 */

namespace AdminBundle\Form\Type;

use AdminBundle\Validator\Recaptcha;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\OptionsResolver\OptionsResolver;

/**
 * Class CaptchaType.
 */
class CaptchaType extends AbstractType
{
    /**
     * @param OptionsResolver $resolver
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'required' => false,
            'mapped' => false,
            'constraints' => [
                new Recaptcha(),
            ],
        ]);
    }

    /**
     * @return string
     */
    public function getName()
    {
        return 'captcha';
    }

    /**
     * @return null|string
     */
    public function getParent()
    {
        return TextType::class;
    }
}

src/AdminBundle/Resources/views/includes/fields.html.twig
{# Widgets #}

{%- block form_widget -%}
    {% if compound %}
        {{- block('form_widget_compound') -}}
    {% else %}
        {{- block('form_widget_simple') -}}
    {% endif %}
{%- endblock form_widget -%}

{%- block form_widget_simple -%}
    {%- set type = type|default('text') -%}
    <input type="{{ type }}" {{ block('widget_attributes') }} {% if value is not empty %}value="{{ value }}" {% endif %}/>
    {%- for attrname, attrvalue in attr %}
        {% if attrname == 'data-addon' %}
            <span class="input-group-addon">{{ attrvalue|raw }}</span>
        {% endif %}
    {%- endfor -%}
{%- endblock form_widget_simple -%}

{%- block form_widget_compound -%}
    <div {{ block('widget_container_attributes') }}>
        {%- if form.parent is empty -%}
            {{ form_errors(form) }}
        {%- endif -%}
        {{- block('form_rows') -}}
        {{- form_rest(form) -}}
    </div>
{%- endblock form_widget_compound -%}

{%- block collection_widget -%}
    {% if prototype is defined %}
        {%- set attr = attr|merge({'data-prototype': form_row(prototype) }) -%}
    {% endif %}
    {{- block('form_widget') -}}
{%- endblock collection_widget -%}

{%- block textarea_widget -%}
    <textarea {{ block('widget_attributes') }}>{{ value }}</textarea>
{%- endblock textarea_widget -%}

{%- block choice_widget -%}
    {% if expanded %}
        {{- block('choice_widget_expanded') -}}
    {% else %}
        {{- block('choice_widget_collapsed') -}}
    {% endif %}
{%- endblock choice_widget -%}

{%- block choice_widget_expanded -%}
    <div {{ block('widget_container_attributes') }}>
        {% for child in form %}
            {{- form_widget(child) -}}
            {{- form_label(child) -}}
        {% endfor %}
    </div>
{%- endblock choice_widget_expanded -%}

{%- block choice_widget_collapsed -%}
    <select {{ block('widget_attributes') }}{% if multiple %} multiple="multiple"{% endif %}>
        {%- if preferred_choices|length > 0 -%}
            {% set options = preferred_choices %}
            {{- block('choice_widget_options') -}}
            {%- if choices|length > 0 and separator is not none -%}
                <option disabled="disabled">{{ separator }}</option>
            {%- endif -%}
        {%- endif -%}
        {%- set options = choices -%}
        {{- block('choice_widget_options') -}}
    </select>
{%- endblock choice_widget_collapsed -%}

{%- block choice_widget_options -%}
    {% for group_label, choice in options %}
        {%- if choice is iterable -%}
            <optgroup label="{{ group_label|trans({}, 'form') }}">
                {% set options = choice %}
                {{- block('choice_widget_options') -}}
            </optgroup>
        {%- else -%}
            <option value="{{ choice.value }}"{% if choice is selectedchoice(value) %} selected="selected"{% endif %}>{{ choice.label|trans({}, 'form') }}</option>
        {%- endif -%}
    {% endfor %}
{%- endblock choice_widget_options -%}

{%- block checkbox_widget -%}
    <input type="checkbox" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{%- endblock checkbox_widget -%}

{%- block radio_widget -%}
    <input type="radio" {{ block('widget_attributes') }}{% if value is defined %} value="{{ value }}"{% endif %}{% if checked %} checked="checked"{% endif %} />
{%- endblock radio_widget -%}

{%- block datetime_widget -%}
    {% if widget == 'single_text' %}
        {{- block('form_widget_simple') -}}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- form_errors(form.date) -}}
            {{- form_errors(form.time) -}}
            {{- form_widget(form.date) -}}
            {{- form_widget(form.time) -}}
        </div>
    {%- endif -%}
{%- endblock datetime_widget -%}

{%- block date_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        <div {{ block('widget_container_attributes') }}>
            {{- date_pattern|replace({
                '{{ year }}':  form_widget(form.year),
                '{{ month }}': form_widget(form.month),
                '{{ day }}':   form_widget(form.day),
            })|raw -}}
        </div>
    {%- endif -%}
{%- endblock date_widget -%}

{%- block time_widget -%}
    {%- if widget == 'single_text' -%}
        {{ block('form_widget_simple') }}
    {%- else -%}
        {%- set vars = widget == 'text' ? { 'attr': { 'size': 1 }} : {} -%}
        <div {{ block('widget_container_attributes') }}>
            {{ form_widget(form.hour, vars) }}{% if with_minutes %}:{{ form_widget(form.minute, vars) }}{% endif %}{% if with_seconds %}:{{ form_widget(form.second, vars) }}{% endif %}
        </div>
    {%- endif -%}
{%- endblock time_widget -%}

{%- block number_widget -%}
    {# type="number" doesn't work with floats #}
    {%- set type = type|default('text') -%}
    {{ block('form_widget_simple') }}
{%- endblock number_widget -%}

{%- block integer_widget -%}
    {% set type = type|default('number') %}
    {{- block('form_widget_simple') -}}
{%- endblock integer_widget -%}

{%- block money_widget -%}
    {{ money_pattern|replace({ '{{ widget }}': block('form_widget_simple') })|raw }}
{%- endblock money_widget -%}

{%- block url_widget -%}
    {%- set type = type|default('url') -%}
    {{ block('form_widget_simple') }}
{%- endblock url_widget -%}

{%- block search_widget -%}
    {%- set type = type|default('search') -%}
    {{ block('form_widget_simple') }}
{%- endblock search_widget -%}

{%- block percent_widget -%}
    {%- set type = type|default('text') -%}
    {{ block('form_widget_simple') }} %
{%- endblock percent_widget -%}

{%- block password_widget -%}
    {%- set type = type|default('password') -%}
    {{ block('form_widget_simple') }}
{%- endblock password_widget -%}

{%- block hidden_widget -%}
    {%- set type = type|default('hidden') -%}
    {{ block('form_widget_simple') }}
{%- endblock hidden_widget -%}

{%- block email_widget -%}
    {%- set type = type|default('email') -%}
    {{ block('form_widget_simple') }}
{%- endblock email_widget -%}

{%- block button_widget -%}
    {%- if label is empty -%}
        {% set label = name|humanize %}
    {%- endif -%}
    <button type="{{ type|default('button') }}" {{ block('button_attributes') }}>{{ label|trans({}, 'form') }}</button>
{%- endblock button_widget -%}

{%- block submit_widget -%}
    {%- set type = type|default('submit') -%}
    {{ block('button_widget') }}
{%- endblock submit_widget -%}

{%- block reset_widget -%}
    {%- set type = type|default('reset') -%}
    {{ block('button_widget') }}
{%- endblock reset_widget -%}

{# Labels #}

{%- block form_label -%}
    {% if label is not same as(false) %}
        {%- if not compound -%}
            {% set label_attr = label_attr|merge({'for': id}) %}
        {%- endif -%}
        {%- if required -%}
            {% set label_attr = label_attr|merge({'class': (label_attr.class|default('') ~ ' required')|trim}) %}
        {%- endif -%}
        {%- if label is empty -%}
            {% set label = name|humanize %}
        {%- endif -%}
        <label{% for attrname, attrvalue in label_attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}>{{ label|trans({}, 'form') }}</label>
    {%- endif -%}
{%- endblock form_label -%}

{%- block button_label -%}{%- endblock -%}

{# Rows #}

{%- block repeated_row -%}
    {#
    No need to render the errors here, as all errors are mapped
    to the first child (see RepeatedTypeValidatorExtension).
    #}
    {{- block('form_rows') -}}
{%- endblock repeated_row -%}

{%- block form_row -%}
    <div class="col-md-6">
        <div class="form-group form-animate-text{% if errors|length > 0 %} form-animate-error{% endif %}">
            {{- form_widget(form) -}}
            <span class="bar"></span>
            {{- form_label(form) -}}
            {{- form_errors(form) -}}
        </div>
    </div>
{%- endblock form_row -%}

{%- block button_row -%}
    <div>
        {{- form_widget(form) -}}
    </div>
{%- endblock button_row -%}

{%- block hidden_row -%}
    {{ form_widget(form) }}
{%- endblock hidden_row -%}

{# Misc #}

{%- block form -%}
    {{ form_start(form) }}
    {{- form_widget(form) -}}
    {{ form_end(form) }}
{%- endblock form -%}

{%- block form_start -%}
    {% set method = method|upper %}
    {%- if method in ["GET", "POST"] -%}
        {% set form_method = method %}
    {%- else -%}
        {% set form_method = "POST" %}
    {%- endif -%}
    <form method="{{ form_method|lower }}" action="{{ action }}"{% for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{% endfor %}{% if multipart %} enctype="multipart/form-data"{% endif %}>
    {%- if form_method != method -%}
        <input type="hidden" name="_method" value="{{ method }}" />
    {%- endif -%}
{%- endblock form_start -%}

{%- block form_end -%}
    {%- if not render_rest is defined or render_rest -%}
        {{ form_rest(form) }}
    {%- endif -%}
    </form>
{%- endblock form_end -%}

{%- block form_enctype -%}
    {% if multipart %}enctype="multipart/form-data"{% endif %}
{%- endblock form_enctype -%}

{%- block form_errors -%}
    {%- if errors|length > 0 -%}
        {%- for error in errors -%}
            <em class="error">{{ error.message }}</em>
        {%- endfor -%}
    {%- endif -%}
{%- endblock form_errors -%}

{%- block form_rest -%}
    {%- for child in form -%}
        {%- if not child.rendered -%}
            {{ form_row(child) }}
        {%- endif -%}
    {%- endfor -%}
{%- endblock form_rest -%}

{# Support #}

{%- block form_rows -%}
    {%- for child in form -%}
        {{ form_row(child) }}
    {%- endfor -%}
{%- endblock form_rows -%}

{%- block widget_attributes -%}
    {% if type is defined and type == 'text' %}
        {%- set attr = attr|merge({'class': (attr.class|default('') ~ ' form-text')|trim}) -%}
    {% endif %}
    id="{{ id }}" {% if errors|length > 0 %}data-error="true" {% endif %}name="{{ full_name }}"{% if disabled %} readonly="readonly"{% endif %}{% if disabled %} disabled="disabled"{% endif %}{% if required %} required="required"{% endif %}{% if max_length is defined %} maxlength="{{ max_length }}"{% endif %}{% if pattern is defined %} pattern="{{ pattern }}"{% endif %}
    {%- for attrname, attrvalue in attr %} {% if attrname in ['placeholder', 'title'] %}{{ attrname }}="{{ attrvalue|trans({}, 'form') }}"{% else %}{{ attrname }}="{{ attrvalue }}"{% endif %}{%- endfor -%}
{%- endblock widget_attributes -%}

{%- block widget_container_attributes -%}
    {% if id is not empty %}id="{{ id }}" {% endif %}
    {%- for attrname, attrvalue in attr %}{{ attrname }}="{{ attrvalue }}" {% endfor -%}
{%- endblock widget_container_attributes -%}

{%- block button_attributes -%}
    id="{{ id }}" name="{{ full_name }}"{% if disabled %} disabled="disabled"{% endif %}
    {%- for attrname, attrvalue in attr %} {{ attrname }}="{{ attrvalue }}"{%- endfor -%}
{%- endblock button_attributes -%}

{%- block captcha_widget -%}
    <div class="g-recaptcha" data-sitekey="{{ captcha_key }}" data-callback="recaptchaCallback"></div>
    <input type="hidden" class="hidden fake-hidden hidden-recaptcha-field" name="hiddenRecaptcha">
{%- endblock -%}

src/AdminBundle/Resources/views/includes/flashbag.html.twig
<script>
    $(document).ready(function() {
        {% for label, messages in app.session.flashbag.all %}
            {% for message in messages %}

                {% if label == 'error' %}
                    {% set label = 'danger' %}
                {% elseif label == 'notice' %}
                    {% set label = 'success' %}
                {% endif %}

                bootoast({
                    message: '{{ message | trans({}, 'notification') }}',
                    type: '{{ label }}'
                });

            {% endfor %}
        {% endfor %}
    });
</script>

src/AdminBundle/Resources/views/includes/footer.html.twig
<div id="mimin-mobile" class="reverse">
    <div class="mimin-mobile-menu-list">
        <div class="col-md-12 sub-mimin-mobile-menu-list animated fadeInLeft" style="overflow: hidden; cursor: grab; height: 100vh!important;" tabindex="5001">
            <ul class="nav nav-list">

                {% include '@Admin/includes/menu.html.twig' %}

            </ul>
        </div>
    </div>
</div>
<button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
    <span class="fa fa-bars"></span>
</button>

    {% javascripts
        'scripts/jquery.min.js'
        'scripts/jquery.ui.min.js'
        'scripts/bootstrap.min.js'
        'scripts/plugins/jquery-validate/dist/jquery.validate.min.js'
        'scripts/plugins/bootoast.js'
        'scripts/plugins/moment.min.js'
        'scripts/plugins/fullcalendar.min.js'
        'scripts/plugins/jquery.nicescroll.js'
        'scripts/plugins/select2.full.min.js'
        'scripts/plugins/fancybox/source/jquery.fancybox.pack.js'
        'scripts/plugins/jquery.ezdz.js'
        'scripts/plugins/blockui.js'
        'scripts/plugins/autosize-master/jquery.autosize.min.js'
        'scripts/plugins/bootstrap-material-datetimepicker.js'
        'scripts/admin/global.js'
        'scripts/admin/custom.js'
        'scripts/admin/ajax.js'
        'scripts/admin/validation.js'
    output='js/app.js' %}
    <script src="{{ asset_url }}"></script>
    {% endjavascripts %}

    {% include '@Admin/includes/javascript-dynamic.html.twig' %}

    <script type='application/ld+json'>
        {
            "@context":"https:\/\/schema.org",
            "@type":"WebSite",
            "@id":"#website",

            "url":"https:\/\/{{ craue_setting('site_nickname') | lower }}.com\/",
            "name":"See my bike"
        }
    </script>
    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-46258175-5"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());

        gtag('config', 'UA-46258175-5');
    </script>


    <!-- Piwik -->
    <script type="text/javascript">
        var _paq = _paq || [];
        /* tracker methods like "setCustomDimension" should be called before "trackPageView" */
        _paq.push(['trackPageView']);
        _paq.push(['enableLinkTracking']);
        (function() {
            var u="//analytics.vsweb.be/piwik/";
            _paq.push(['setTrackerUrl', u+'piwik.php']);
            _paq.push(['setSiteId', '14']);
            var d=document, g=d.createElement('script'), s=d.getElementsByTagName('script')[0];
            g.type='text/javascript'; g.async=true; g.defer=true; g.src=u+'piwik.js'; s.parentNode.insertBefore(g,s);
        })();
    </script>
    <!-- End Piwik Code -->

<div class="microdatas hidden" itemscope itemtype="https://schema.org/Corporation">
    <h1 itemprop="name">See my bike</h1>
    <p itemprop="description">See my bike,
        découvre ce que vaut ta machine,
        qui a vu le jour en <time itemprop="foundingDate" datetime="2016-01-01">2016</time>
        par <span itemprop="founders">Jul6art</span>
        et qui se trouve à Liège, en Belgique.</p>
    <span itemprop="location" itemscope itemtype="https://schema.org/Place">
		<meta itemprop="name" content="See my bike par VsWeb">
		<meta itemprop="address" content="1 rue des Guillemins, 4000 Liège Belgique">
	</span>
    <p itemprop="contactPoint" itemscope itemtype="https://schema.org/ContactPoint">
        <meta itemprop="contactType" content="customer support">
        <span itemprop="telephone">+32497189998</span>
    </p>
    <p><a href="https://{{ craue_setting('site_nickname') | lower }}.com" itemprop="url">https://{{ craue_setting('site_nickname') | lower }}.com</a></p>
    <ul itemprop="employees" itemscope itemtype="https://schema.org/Person">
        <li><p itemprop="name">VsWeb</p><a href="https://vsweb.be" itemprop="url">https://vsweb.be</a></li>
    </ul>
    <ul itemprop="employees" itemscope itemtype="https://schema.org/Person">
        <li><p itemprop="name">Jul6art</p><a href="https://kratz.deepweb.be" itemprop="url">https://kratz.deepweb.be</a></li>
    </ul>
</div>

{% if app.user and is_granted('ROLE_PREVIOUS_ADMIN') %}
    <div class="fixed-impersonate">
        <div class="impersonate">
            <div>
                <i class="fa fa-info-circle fa-2x"></i>
            </div>
            <div>
                <p>
                    {{ 'impersonate.text' | trans({
                        '%username%': app.user.username|title,
                        '%email%': app.user.email,
                        '%url%': path('admin_user_list', {'_switch_user': '_exit'})
                    }, 'impersonate') | raw }}
                </p>
            </div>
        </div>
    </div>
{% endif %}


src/AdminBundle/Resources/views/includes/header.html.twig
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="{{ asset('stylesheets/font-awesome.min.css') }}"/>
    {% stylesheets
    'stylesheets/bootstrap.min.css'
    'stylesheets/plugins/bootoast.css'
    'stylesheets/plugins/simple-line-icons.css'
    'stylesheets/plugins/animate.min.css'
    'stylesheets/plugins/fullcalendar.min.css'
    'stylesheets/plugins/select2.min.css'
    'stylesheets/plugins/bootstrap-material-datetimepicker.css'
    'scripts/plugins/fancybox/source/jquery.fancybox.css'
    'stylesheets/plugins/jquery.ezdz.css'
    'stylesheets/plugins/flags.min.css'
    'stylesheets/admin/style.css'
    'stylesheets/admin/custom.css'
    output='css/app.css' %}
    <link rel="stylesheet" type="text/css" href="{{ asset_url }}"/>
    {% endstylesheets %}

    {% block stylesheets %}
    {% endblock stylesheets %}

    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Google Recaptcha -->
    <script src="https://www.google.com/recaptcha/api.js"></script>
</head>
<body id="mimin" class="dashboard">
    <!-- start: Header -->
    <nav class="navbar navbar-default header navbar-fixed-top">
        <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
                <div class="opener-left-menu is-open">
                    <span class="top"></span>
                    <span class="middle"></span>
                    <span class="bottom"></span>
                </div>
                <a href="{{ path('app_home') }}" class="navbar-brand">
                    <b>{{ craue_setting('site_nickname') | upper }}</b>
                </a>

                <ul class="nav navbar-nav search-nav">
                    <li>
                        <div class="search">
                            <span class="fa fa-search icon-search" style="font-size:23px;"></span>
                            <form class="form-group form-animate-text" action="{{ path('api_search') }}" method="post">
                                <input type="text" class="form-text" name="recherche" required value="{% if app.request.query.has("searchString") %}{{ app.request.query.get("searchString") }}{% endif %}">
                                <span class="bar"></span>
                                <label class="label-search">{{ 'app.search.placeholder' | trans({}, 'app') | raw }} </label>
                            </form>
                        </div>
                    </li>
                </ul>

                <ul class="nav navbar-nav navbar-right user-nav">
                    <li class="user-name">
                        <span>
                            {% if app.user %}
                                {{ app.user.username }}
                            {% endif %}
                        </span>
                    </li>
                    <li class="dropdown avatar-dropdown">
                        <img src="{{ asset('img/avatar.jpg') }}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true"/>
                        <ul class="dropdown-menu user-dropdown">
                            <li class="more">
                                <ul>
                                    <li><a href="{{ path('app_home') }}" data-toggle="tooltip" data-placement="left" title="" data-original-title="{{ 'navbar.home' | trans({}, 'navbar') }}">
                                            <span class="icons icon-home"></span>
                                        </a>
                                    </li>
                                    {% if app.user %}
                                        <li>
                                            <a href="{{ path('fos_user_change_password') }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ 'navbar.change_password' | trans({}, 'navbar') }}">
                                                <span class="icons icon-key"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{{ path('fos_user_security_logout') }}" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ 'navbar.logout' | trans({}, 'navbar') }}">
                                                <span class="icons icon-power"></span>
                                            </a>
                                        </li>
                                    {% else %}
                                        <li>
                                            <a href="{{ path('fos_user_registration_register') }}" data-toggle="tooltip" data-placement="top" title="" data-original-title="{{ 'navbar.register' | trans({}, 'navbar') }}">
                                                <span class="icons icon-key"></span>
                                            </a>
                                        </li>
                                        <li>
                                            <a href="{{ path('fos_user_security_login') }}" data-toggle="tooltip" data-placement="bottom" title="" data-original-title="{{ 'navbar.login' | trans({}, 'navbar') }}">
                                                <span class="icons icon-power"></span>
                                            </a>
                                        </li>
                                    {% endif %}
                                </ul>
                            </li>
                        </ul>
                    </li>
                    {% if app.user %}
                        <li><a href="#" class="opener-right-menu"><span class="fa fa-coffee"></span>{{ notification(app.user, 'userNotifications') }}</a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <!-- end: Header -->

src/AdminBundle/Resources/views/includes/javascript-dynamic.html.twig
{% if app.request.locale != 'en' %}
    <script src="{{ asset('scripts/plugins/jquery-validate/dist/localization/messages_'~app.request.locale~'.js') }}" type="text/javascript"></script>
{% endif %}
<script>
    $.extend($.validator.messages, {
        captcha: "{{ 'form.user.captcha' | trans({}, 'javascript') }}",
        repeated_password: "{{ 'form.user.repeated_password' | trans({}, 'javascript') }}",
        user_email_exists: "{{ 'form.user.user_email_exists' | trans({}, 'javascript') }}"
    });

    $(document).ready(function () {
        initPickers();
        initSelect2();
        dropFile();
    });

    function initPickers() {
        $('input.date').bootstrapMaterialDatePicker({
            weekStart : 1,
            lang: '{{ app.request.locale }}',
            time: false,
            clearButton: true,
            cancelText: "{{ 'picker.cancel_text' | trans({}, 'javascript') }}",
            clearText: "{{ 'picker.clear_text' | trans({}, 'javascript') }}",
            okText: "{{ 'picker.ok_text' | trans({}, 'javascript') }}",
        });

        $('input.time').bootstrapMaterialDatePicker({
            date: false,
            lang: '{{ app.request.locale }}',
            format:'HH:mm',
            animation:true,
            clearButton: true,
            cancelText: "{{ 'picker.cancel_text' | trans({}, 'javascript') }}",
            clearText: "{{ 'picker.clear_text' | trans({}, 'javascript') }}",
            okText: "{{ 'picker.ok_text' | trans({}, 'javascript') }}",
        });

        $('.datetime').bootstrapMaterialDatePicker({
            weekStart : 1,
            lang: '{{ app.request.locale }}',
            format : 'YYYY-MM-DD HH:mm',
            animation:true,
            clearButton: true,
            cancelText: "{{ 'picker.cancel_text' | trans({}, 'javascript') }}",
            clearText: "{{ 'picker.clear_text' | trans({}, 'javascript') }}",
            okText: "{{ 'picker.ok_text' | trans({}, 'javascript') }}",
        });
    }

    function initSelect2() {
        $('.select2').select2({
            placeholder: "{{ 'select2.placeholder' | trans({}, 'javascript') }}",
            allowClear: true,
            minimumResultsForSearch: Infinity
        });

        $('.select2-search').select2({
            placeholder: "{{ 'select2.placeholder' | trans({}, 'javascript') }}",
            allowClear: true
        });

        $('.select2-ajax').each(function () {
            $(this).select2({
                ajax: {
                    url: $(this).data('url'),
                    dataType: 'json'
                },
                delay: 250,
                minimumInputLength: 1,
                placeholder: "{{ 'select2.placeholder' | trans({}, 'javascript') }}",
                allowClear: true,
                language: {
                    searching: function(params) {
                        query = params;
                    }
                }
            });
        });
    }

    function dropFile () {
        $('input[type="file"]').ezdz({
            text: "{{ 'dropfile.text' | trans({}, 'javascript') }}",
            validators: {
                maxSize: 24000000,
                maxNumber: 15
            },
            reject: function(file, errors) {
                if (errors.mimeType) {
                    alert(file.name + " {{ 'dropfile.error.filetype' | trans({}, 'javascript') }}");
                    return;
                }

                if (errors.maxSize) {
                    alert(file.name + " {{ 'dropfile.error.size' | trans({}, 'javascript') }}");
                    return;
                }

                if (errors.maxNumber) {
                    alert("{{ 'dropfile.error.count' | trans({}, 'javascript') }}");
                    return;
                }
            }
        });
    }
</script>